apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: checkout-network-loss
  namespace: default
spec:
  action: loss
  mode: one
  selector:
    labelSelectors:
      app: checkout
  loss:
    loss: "10"
    correlation: "100"
  duration: "5m"
  scheduler:
    cron: "@every 10m"
